//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bdl_Grupo2_ProyectoFinal_A
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        public int Eqs_Id { get; set; }
        public string Eqs_Codigo { get; set; }
        public Nullable<int> Hdw_Id { get; set; }
        public Nullable<int> Sfw_Id { get; set; }
        public Nullable<int> Usr_Id { get; set; }
        public int aceptado { get; set; }
    
        public virtual Hardware Hardware { get; set; }
        public virtual Software Software { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
